apiVersion: v1
kind: Pod
metadata:
  name: sensitive-mount-pod
  labels:
    app: sensitive-test
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /sensitive-data
      name: sensitive-volume
  volumes:
  - name: sensitive-volume
    hostPath:
      path: /root # This matches one of the paths in your macro
      type: DirectoryOrCreate
